### PR TITLE
Remove groupBy DQL part for datatable count methods

### PR DESCRIPTION
**Pull request by zgoniaiko**
In case DQL got `groupBy` part somehow (callback, set query etc), `->getSingleScalarResult()` will fail with `The query returned multiple rows`.

Issue persists both on v.0.10 and on master.
This pull fix issue for master only.

### CODE REVIEW

**Comment by zgoniaiko** [comment]
@stwe can you please backport it to v.0.10 or give some workaround for that version?

**Comment by stwe** [comment]
Why backport? You can use dev-master or wait some days for 0.11.

**Comment by zgoniaiko** [comment]
@stwe I added backport branch to my fork as temp solution, so I can stay on 0.10 and have that issue fixed at same time.

I'm ok to wait for 0.11 (I didn''t known it will be released in next few days).

**Comment by stwe** [comment]
My `groupBy` fails for other reasons. Please give me your example so I can see where the problem is.

**Comment by zgoniaiko** [comment]
@stwe we can add `groupBy` part that way for example

```
    $datatable = $this->get('app.datatable.comment');
    $datatable->buildDatatable();

    $query = $this->get('sg_datatables.query')->getQueryFrom($datatable);

    $function = function($qb)
    {
        $qb->addGroupBy("post.id");
    };

    $query->addWhereAll($function);

    return $query->getResponse();
```

and it will fail with

```
 The query returned multiple rows. Change the query or use a different result function like getScalarResult().
500 Internal Server Error - NonUniqueResultException 
```

**Comment by stwe** [comment]
I have made some tests with `groupBy`. Your patch eliminates the error message. However, the total number of records is not true in some cases.

**Comment by zgoniaiko** [comment]
@stwe it what cases it give wrong total nums?

**Comment by zgoniaiko** [comment]
@stwe it show wrong numbers for you in case group by root id?

**Comment by edsonlimadev** [comment]
I have the same problem U.U
We can use this strategy to fix the count problem:

```php
        return !$qb->getDQLPart('groupBy') ?
            (int) $qb->getQuery()->getSingleScalarResult()
            : count($qb->getQuery()->getResult());
```

**Comment by Bruce17** [comment]
I provided also a fix, see https://github.com/stwe/DatatablesBundle/pull/467.

**Comment by stwe** [comment]
Done in dev-master

**Pull request closed without merging**
