### PR TITLE
Doctrine Cache support

### PR DESCRIPTION
**Pull request by Eloar**
- Added Doctrine Cache support to DatatableQueryBuilder
- Cache usage documented in cache.md doc file

### CODE REVIEW

**Comment by stwe** [comment]
Thanks. Currently I have the following doctrine setup in my config.yml

``` yml
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
```

Which doctrine setup do you recommend for doctrine caching? I think this is important for the documentation.

**Comment by Eloar** [comment]
I've added `Doctrine` and `DoctrineCacheBundle` configuration description in cache.md file. Let me know if it might be enhanced in any way.

**Comment by stwe** [comment]
Thank you. Do you have any measurable positive results ind prod mode?

**Comment by Eloar** [comment]
Well not many but one of our datatables (most frequent) used got cache support turned on and set for files. Datatable count query took roughly 200ms on average and cache hit takes 20ms on average.

**Comment by stwe** [comment]
I believe that. But in dev mode the doctrine caching is deactivated. How did you determine the times?

**Comment by Eloar** [comment]
and we got average ~15% request time gain when turned cache on for data retrieval query

**Comment by Eloar** [comment]
I've used XHprof, Firebug/FF debug console/Chrome debug console and Apache Debug (ad) to measure times. Implementation of cache in DataTable is part of optimization process we are running for one of our applications. 

As far as I observed even in Symfony Profiler I could see difference between cache hit and cache miss requests, but maybe our dev env is just set up wrong.

**Pull request merged**
