### PR TITLE
Added the option to provide 'callbacks' for the DataTables javascript…

### PR DESCRIPTION
**Pull request by hoimic**
When using the DataTables javascript library, the developer can provide callbacks to execute javascript functions after certain events have been triggered (e.g. the DataTable has been drawn). However, the stwe/DatatablesBundle lacked support for this feature. The current branch provides this functionality

### CODE REVIEW

**Comment by stwe** [comment]
Thanks. Is there any example for the docs?

**Comment by mennowame** [comment]
@stwe Is there some way we can improve this so we can get this merged? We think this is needed to use the default DataTables callbacks as described here: https://datatables.net/reference/option/
Or is there some better way to do that with this bundle?

**Comment by stwe** [comment]
the pr #136 is in the master branch.....
Am 16.06.2015 11:14 schrieb "Menno van der Werff" <notifications@github.com

**Comment by mennowame** [comment]
Ok sorry, I didn't see that. Thanks for merging :+1:

**Pull request closed without merging**
