### PR TITLE
date range individual filtering and others

### PR DESCRIPTION
**Pull request by DarekTw**
added:
 - date range individual filtering to DatatableQuery
 - route_parameters and attributes to MultiselectAction
 - definable value to MultiselectColumn based on 'colum name key'
 - AuthorizationChecker service to AbstractDatatableView - needed for voters
 - multiple ordering format to Options example: [[0, "asc"], [1, "desc"]] 
 - refactored multi-select_actions.html.twig and options.html.twig
 - striptags + trim in individual filtering

---------------------
definable value to MultiselectColumn based on 'colum name key'
The problem was on the random order of columns
wstep16
wstep17

so the bulk multi-actions (disable delete) not always have proper parameter (id)

---------------------
date range individual filtering is recognized by column name 'daterange' 
https://github.com/stwe/DatatablesBundle/pull/111/files#diff-b5651708ab6262bc90d9ed2508ccda7aR328 
I use for this external calendar script http://www.daterangepicker.com/

### CODE REVIEW

**Comment by DarekTw** [comment]
definable value to MultiselectColumn based on 'colum name key'
The problem was no order of columns, it was random
wstep16
wstep17

so the bulk multi-actions (disable delete) not always have proper parameter (id)

**Comment by stwe** [comment]
Thank you.
I think that "daterange" should be a new column type.

**Comment by DarekTw** [comment]
it should be :)
but how discover a colum type in dataquery?

**Comment by stwe** [comment]
I have a problem with encoding and the daterange filter. Any idea?

see:

unbenannt

**Comment by DarekTw** [comment]
it is strange, maybe you should try define locale http://www.daterangepicker.com/#ex5
```
        locale: {
            applyLabel: 'Submit',
            cancelLabel: 'Cancel',
            fromLabel: 'From',
            toLabel: 'To',
            customRangeLabel: 'Custom',
            daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr','Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            firstDay: 1
        }

```

**Comment by stwe** [comment]
the following works:

            <script type="text/javascript">
                $( document ).ready(function() {
                    moment.locale("de");
                    $('input[name="daterange"]').daterangepicker();
                });
            </script>

**Pull request merged**
