### PR TITLE
Update DatatableQueryBuilder.php to fix #936 (null value in setSelectSearchType)

### LINKED ISSUE #936: Exception: null value for setSelectSearchType
I just got an exception with a specific search:

`Uncaught PHP Exception TypeError: "Argument 1 passed to Sg\DatatablesBundle\Datatable\Filter\SelectFilter::setSelectSearchType() must be of the type string, null given, called in (...)\vendor\sg\datatablesbundle\Datatable\Filter\SelectFilter.php on line 74" at (...)\vendor\sg\datatablesbundle\Datatable\Filter\SelectFilter.php line 174`

The options in the search-dropdown are all strings (and an empty string for "show all") but no NULL-value (as suggested in the exception message), so the question is, how is it even possible to have NULL as a search string in a select filter? Unfortunately I can't reproduce error.

Suggestion for a quick fix: Casting $searchValue to string in SelectFilter (line 74)?

Using dev-master with Symfony 4.4.5 and PHP 7.3.13

### PR DESCRIPTION
**Pull request by Knallcharge**
it's possible for a null value to sneak through "addAndExpression", fixes #936

### CODE REVIEW

**Comment by Seb33300** [comment]
I think this should be fixed here: 
https://github.com/stwe/DatatablesBundle/blob/master/Response/DatatableQueryBuilder.php#L534

**Comment by Knallcharge** [comment]
fine with me :)

**Comment by Seb33300** [comment]
I think `'null' !== $searchValue` was a mistake.
I think you can remove it.

We should be able to search for `'null'` string.

**Comment by Knallcharge** [comment]
done

**Pull request merged**
