### PR TITLE
check details

### PR DESCRIPTION
**Pull request by renearias**
integrated whith details

### CODE REVIEW

**Comment by stwe** [comment]
Thank you for your work. Currently it is not possible for me for work reasons to review the many changes (876 additions). I'll do it as soon as possible.

**Comment by mennowame** [comment]
@renearias maybe you can already clean-up the pull request to make it easier for stwe to review. I didnt test this, but quickly looked at the code. Some improvements:
- remove netbeans specific files
- avoid html in translation files
- spaces in Resources/views/Datatable/datatable_html.html.twig row 10
- remove console.log in Resources/views/Datatable/detailsfunction.html.twig (if not needed)

**Comment by renearias** [comment]
thank i was updated these changes now

**Comment by stwe** [comment]
@renearias Thank you for your work on this bundle. I'll look at the next weekend.

**Comment by renearias** [comment]
check the new changes please

**Comment by mennowame** [comment]
@renearias These changes are quite difficult to compare because you mixed your changes with previous commits that have already been merged. Maybe rebase your commits, so only your changes are visible. I did see some minor things:
* check the casing of the variables you create. Examples: $toajax should be $toAjax, $visibleonrow should be $visibleOnRow
* remove your personal .gitignore 

Please note: I didn't test these commits and didn't look trough all changes

**Pull request closed without merging**
