### PR TITLE
Made templates compatible with twig 2.

### PR DESCRIPTION
**Pull request by vctls**
Changed usage of `_self` according to the twig 2 documentation.
I tested this with both twig 1 and 2, and it doesn't seem to break BC.

### CODE REVIEW

**Comment by foaly-nr1** [comment]
The variable name `forms` makes sense in the [example from the Twig documentation](https://twig.sensiolabs.org/doc/2.x/tags/macro.html#import) because the template the macros are being imported from is `forms.html`.

```
{% import "forms.html" as forms %}
```

In this case, I'd suggest using a different variable name, e.g. `macros`.

```
{% import _self as macros %}
```

**Comment by vctls** [comment]
@foaly-nr1 you're right. Shall I change my PR?

**Comment by foaly-nr1** [comment]
Was this a question to @stwe? I'd suggest yes :)

**Comment by stwe** [comment]
i'll take a look. First I have to install twig 2 :)

**Pull request closed without merging**
