### PR TITLE
Set dom when use_integration_options = true

### LINKED ISSUE #206: Set dom when use_integration_options = true
When ``use_integration_options`` is set to ``true``, ``dom`` is ignored. I think you should be able to change it anyway.

It's also useful for https://github.com/stwe/DatatablesBundle/issues/203.

### PR DESCRIPTION
**Pull request by stephanvierkant**
Fixes #206

### CODE REVIEW

**Comment by stwe** [comment]
@migmolrod is right. The integration options use their own 'dom' .

Example: https://cdn.datatables.net/plug-ins/1.10.9/integration/bootstrap/3/dataTables.bootstrap.js

```js
/* Set the defaults for DataTables initialisation */
$.extend( true, DataTable.defaults, {
	dom:
		"<'row'<'col-sm-6'l><'col-sm-6'f>>" +
		"<'row'<'col-sm-12'tr>>" +
		"<'row'<'col-sm-5'i><'col-sm-7'p>>",
	renderer: 'bootstrap'
} );
```

**Comment by stephanvierkant** [comment]
Why is this unmerged? It isn't possible to configure your own dom right now.

**Comment by stwe** [comment]
Because the extension can no longer set the dom automatically.

Try to set the dom in your controller:

```php
    public function indexAction()
    {
        $datatable = $this->get('app.datatable.post');
        $datatable->buildDatatable();
        $datatable->getOptions()->setOptions(array('dom' => 'your dom string'));

        return array(
            'datatable' => $datatable,
        );
    }
```

**Comment by stephanvierkant** [comment]
Sorry, I don't know what's the problem. I changed the lines in my own projects and it works perfectly. You should be able to set the dom with some extra information (like the buttons I mentioned).

**Comment by stwe** [comment]
For `Integration Options === true`
This is one of my ideas: Render the buttons automatically with the init event.

```php
            'extensions' => array(
                'buttons' => array(
                    /*
                    array(
                        'extend' => 'pdf',
                        'text' => 'Save as PDF'
                    ),
                    */
                    'pdf',
                    'excel'
                ),
                'responsive' => true
            )
```

```js
                {% if view_features.extensions.buttons is defined %}
                    {% if true == view_options.useIntegrationOptions %}
                        .on('init.dt',
                            function() {
                                new $.fn.dataTable.Buttons(oTable, {
                                    "buttons": {% for option in view_features.extensions.buttons %}[{{ option|json_encode|raw }}]{% endfor %}
                                });

                                if ('bootstrap' == oTable.context[0].renderer) {
                                    oTable.buttons().container().appendTo('#' + oTable.table().container().id + ' .col-sm-6:eq(0)');
                                }

                                if ('foundation' == oTable.context[0].renderer) {
                                    oTable.buttons().container().appendTo('#' + oTable.table().container().id + ' .small-6.columns:eq(0)');
                                }

                                if ('jqueryui' == oTable.context[0].renderer) {
                                    oTable.buttons().container().appendTo('#' + oTable.table().container().id);
                                }
                            }
                        )
                    {% endif %}
                {% endif %}
```

**Comment by stephanvierkant** [comment]
I still don't know what's wrong with my PR. It's working for me, without your workaround.

**Comment by BigZ** [comment]
the problem is that you are breaking the semantic option "use_integration_options" which means the datatable should use options from integration.
we could create another option specifically for the dom.

**Comment by BigZ** [comment]
new pull request on this topic https://github.com/stwe/DatatablesBundle/pull/233

**Comment by stwe** [comment]
@stephanvierkant 

This part of the bootstrap extension is to be set automatically :

```js
/* Set the defaults for DataTables initialisation */
$.extend( true, DataTable.defaults, {
	dom:
		"<'row'<'col-sm-6'l><'col-sm-6'f>>" +
		"<'row'<'col-sm-12'tr>>" +
		"<'row'<'col-sm-5'i><'col-sm-7'p>>",
	renderer: 'bootstrap'
} );
```
With these settings , this is done correctly:

```php
'use_integration_options' => true
```

This is the result of `true`

use_integration

With the following settings you have access to the `dom`. But the extension is not used correctly . The `dom` is wrong . The `renderer` is not used .

```php
'use_integration_options' => false
```

Result:

no_integration

**Comment by stwe** [comment]
see and try #234

**Pull request closed without merging**
