### PR TITLE
Adding Symfony 4 support

### PR DESCRIPTION
**Pull request by samuel4x4**
#SymfonyConHackday2017

### CODE REVIEW

**Comment by samuel4x4** [comment]
@stwe @Seb33300

**Comment by Seb33300** [comment]
Hi,

Thank you for your contribution.

Did you checked the part related to [DependencyInjection](https://github.com/symfony/symfony/blob/master/UPGRADE-4.0.md#dependencyinjection)?

Services are private by default with SF4, and this bundle declare multiple services:
https://github.com/stwe/DatatablesBundle/blob/master/Resources/config/services.yml

I think ` sg_datatables.factory` should be public, not sure for the others.

**Comment by samuel4x4** [comment]
Hi @Seb33300, I'll check that, and if I have time I'll add some unit tests for those services ;)

**Comment by samuel4x4** [comment]
thanks @Seb33300 ;)

**Pull request merged**
