### PR TITLE
Added php-cs-fixer

### LINKED ISSUE #907: Coding style
I think we should decide on a coding style so we can automate the process of bitching about spaces, indenting, etc. and have a better, cleaner and easier to read and maintain code. 

I don't like the Symfony Coding Standard for some reasons. I don't like the Yoda comparison, but that's a personal preference. More important: `FriendsOfPHP/PHP-CS-Fixer` lacks features `squizlabs/PHP_CodeSniffer` has.

Some ideas to improve the coding style:
* Remove useless docblocks like '{class} Constructor', `@package` annotation
* Remove `@param` or `@return` if native PHP types are using.
* Type hinting/return types when possible (for now: only only private methods because BC)
* Use short array syntax
* Remove redundant `else` (early return/exit)

I'll work on a PR to improve this, so please let me know if you have a opinion about this matter.

### PR DESCRIPTION
**Pull request by stephanvierkant**
I've added a php-cs-fixer configuration to create (and keep) a consistent coding style, so we don't have to argue about spaces, indenting, etc. at every single PR.

Some type hinting is added, but only on private methods, because of BC.

I've used the`@Symfony` ruleset, but with some additional rules. Coding style is always a matter of personal preferences, so please let me know what you think.

Fixes #907

### CODE REVIEW

**Comment by mwansinck** [comment]
+1 four using a standaard code style and updating the code base. At our company we use the PSR1/PSR2 code style (from PhpStorm iDEA) instead of the Symfony one.

Personally I don't prefer the backslash for native PHP functions (`if (\count($actions)` and adding a dot in a DocBlock doesn't always feel logic `* Default: '#FFFF80'.`

**Comment by stephanvierkant** [comment]
I prefer the Doctrine coding style (and I prefer phpcs), but since this is a bundle I think it's better to stick to the `@Symfony` rules.

I've read that it is (slightly) faster to either use a slash or use `use count;`, but I've no idea if that's (still) true. Nevermind, in this case I was lazy and sticked to the Symfony guidelines without really having an opinion about this.

The trailing dot doesn't really make sense indeed. Maybe because it enforces you to write sentences instead of some random words if a comment has to end with a dot? In case of the default '#FFFF80': some extra information would have been nice, because where is that default set? It doesn't say 'protected $highlight = '#FFFF80';

**Comment by mwansinck** [comment]
In the end I don't mind which style is being used, using a style anyway is a good idea anyway.
Maybe instructions for other contributors should be added to the README.md

**Comment by Seb33300** [comment]
> I've used the@Symfony ruleset, but with some additional rules.
Can you list the additional rules you added?

**Comment by stephanvierkant** [comment]
> > I've used the@Symfony ruleset, but with some additional rules.
> > Can you list the additional rules you added?

The rules are in `.php_cs.dist`. I just removed some duplicate rules so it's clear which are added by me.

**Pull request merged**
