### PR TITLE
Fix search/filtering to use every filter in "dataTables_wrapper"

### PR DESCRIPTION
**Pull request by Bruce17**
Fixes issue https://github.com/stwe/DatatablesBundle/issues/662

### CODE REVIEW

**Comment by Seb33300** [comment]
I am trying to reproduce this issue, how do you change the dom layout?

**Comment by Bruce17** [comment]
Have a look at the [doc](https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/options.md), parameter "dom". Also have a look at the datatables doc for that.

**Comment by Seb33300** [comment]
Can you give me an example value of dom option to reproduce your issue?

**Comment by Bruce17** [comment]
Sry for the delay, I was out of office a few days.

Here is my dom setting:
```
<'row'<'#datatables-toolbar.col'><'col' lf>>
<'row'<'col' tr>>
<'row'<'col-4' i><'col-8' p>>
```

**Comment by Bruce17** [comment]
@stephanvierkant This ticket is not about indents. I can revert them if you like.

**Comment by Seb33300** [comment]
Do I need to do something else?

In my datatable class I set this, but nothing special happens:
``` php
$this->options->setDom("<'row'<'#datatables-toolbar.col'><'col' lf>>
<'row'<'col' tr>>
<'row'<'col-4' i><'col-8' p>>");
```

**Comment by Bruce17** [comment]
Well actually I can’t post my application code. There some other parts.

Let me check what I can post in addition to this…

Von: Sébastien ALFAIATE
Gesendet: Donnerstag, 16. November 2017 10:54
An: stwe/DatatablesBundle
Cc: Michael; Author
Betreff: Re: [stwe/DatatablesBundle] Fix search/filtering to use every filterin "dataTables_wrapper" (#663)

Do I need to do something else?
In my datatable class I set this, but nothing special happens:
$this->options->setDom("<'row'<'#datatables-toolbar.col'><'col' lf>>
<'row'<'col' tr>>
<'row'<'col-4' i><'col-8' p>>");

**Comment by Bruce17** [comment]
This is the complete setup I'm using:

```php
protected function prepareOptions(array $additionalOptions = array())
{
	$domRowStyling = "<'row'<'#datatables-toolbar.col' B><'col' lf>>";
	$domRowStyling .= "<'row'<'col' tr>>";
	$domRowStyling .= "<'row'<'col-4' i><'col-8' p>>";

	$this->options->set(
		array_merge(
			array(
				'display_start'                 => 0,
				'dom'                           => $domRowStyling,
				'length_menu'                   => array(10, 25, 50, 100),
				'order_classes'                 => true,
				'order'                         => array(array(1, 'asc')),
				'order_multi'                   => true,
				'order_cells_top'               => true,
				'page_length'                   => 25,
				'paging_type'                   => Style::FULL_NUMBERS_PAGINATION,
				'renderer'                      => 'bootstrap',
				'scroll_collapse'               => false,
				'search_delay'                  => 1000,
				'state_duration'                => 7200,
				'stripe_classes'                => [],
				'classes'                       => join(
					' ',
					[
						Style::BOOTSTRAP_4_STYLE,
						'table-hover',
					]
				),
				'search_in_non_visible_columns' => true,
				'individual_filtering'          => true,
				'individual_filtering_position' => 'head',
			),
			$additionalOptions
		)
	);
}
```

**Comment by Seb33300** [comment]
Still not able to reproduce your issue.
Can you send a screenshot of your rendered datatable?

How are defined filters which are outside from the `dataTables_wrapper`

**Pull request closed without merging**
