### PR TITLE
Fix: recordsTotal calculation issue

### LINKED ISSUE #639: recordsTotal calculation issue
Hi,

I noticed that now `\Sg\DatatablesBundle\Response\DatatableQueryBuilder::getCountAllResults` method do not add `$this->setWhereAllCallback($qb);` as in previous bundle version, which was useful for showing correct filtered count, because now it just counts all results in database table and do not add any custom queries. What was the reason of removing it? Maybe now there is another way to solve this issue?

Thanks. 

Great bundle by the way! :)

### PR DESCRIPTION
**Pull request by ronisaha**
To fix #639 we can use doctrine Criteria instead of modifying query builder. 

criteria is more reusable.
I've defined a baseCriteria  property to perform the base filter and other filter option should be used as it is.
This way the total count would be as per user expectation.

### CODE REVIEW

**Comment by Seb33300** [comment]
recordsTotal calculation issue should be fixed even if we don't use a Criteria to filter the DatatableQueryBuilder.

**Comment by ronisaha** [comment]
What would be the implementation? It's a common implementation to provide a base filter which should be used in  counting total records. 

Lets assume a scenario:

We have 20 rows in a table. The record has some categorization let say department(Dept1, Dept2). And we want to show only 15 records which belongs to logged in user's department dept1. 

So if we use the query builder to filter out the five records, the info would show us 15 records filtered from 20 records. but its not correct. The total count should be 15 instead of 20.

Thanks

**Comment by Seb33300** [comment]
If we want to filter the query builder, we can just modify it as explained here:
https://github.com/stwe/DatatablesBundle/issues/604

`getCountAllResults()` should make the count on the current query builder instead of creating a new one.

**Comment by ronisaha** [comment]
No it will not serve the example use case.
This PR doesn't creating another new query builder. It is reusing the already created one [here](https://github.com/stwe/DatatablesBundle/blob/ddc2cb3af707d46ba00cd480ca222378aaf80c77/Response/DatatableQueryBuilder.php#L533)

Modifying the query builder like explained here: #604
Will show the count in recordsFiltered count. And total count will use another query builder(which is fine) to get all records count. see [here](https://github.com/stwe/DatatablesBundle/blob/ddc2cb3af707d46ba00cd480ca222378aaf80c77/Response/DatatableResponse.php#L144-L145). 

If you look from the table prospective its correct, indeed we are showing 15 records filtered from 20 but from user perspective the table should have only 15 records. So the message is incorrect.

**Comment by Seb33300** [comment]
> It is reusing the already created one [here](https://github.com/stwe/DatatablesBundle/blob/ddc2cb3af707d46ba00cd480ca222378aaf80c77/Response/DatatableQueryBuilder.php#L533)

Wrong.

```
$qb = $this->em->createQueryBuilder();
```

`createQueryBuilder` as indicated by his name, create a new query builder.

**Comment by ronisaha** [comment]
:smile:  You have mentioned the same piece of code I have mentioned in my comment.

So is there  a existing PR or Work in progress issue to remove this extra(!) query builder?.

> ` $this->em->createQueryBuilder();`

Will that issue/PR also solve this issue?

Thanks!

**Comment by ronisaha** [comment]
To explain the difference and the bug, I've created a test repo https://github.com/ronisaha/DataTableIssueTest 
The **master** and **fet-criteria** branch has two implementation. You can check the difference in **Own Posts** Link
In master branch its showing 

> Showing 1 to 10 of 42 entries (filtered from 100 total entries)

And in fet-criteria branch the info message is

> Showing 1 to 10 of 42 entries

And if we apply any filter or global search it will show something like

> Showing 1 to 10 of 22 entries (filtered from 42 total entries)

**Comment by Seb33300** [comment]
I know the difference.
But filtered elements are defined in the `setWhere()`, so we just have to not apply this to make the count.

**Pull request closed without merging**
