### PR TITLE
Rename type to method

### PR DESCRIPTION
**Pull request by stephanvierkant**

### CODE REVIEW

**Comment by Seb33300** [comment]
`GET` is the default value in:

``` javascript
var conf = $.extend( {
        pages: 5,     // number of pages to cache
        url: '',      // script url
        data: null,   // function or object with parameters to send to the server
                      // matching how `ajax.data` works in DataTables
        method: 'GET' // Ajax HTTP method
}, opts );
```

`$.extend` will override the default value with `opts.type` if defined.

**Comment by Seb33300** [comment]
Hmmm.

Just see you used `opts.type` and not `opts.method`.
How is defined this option?

**Comment by stephanvierkant** [comment]
There is no `opts.method`, it's `opts.type`. This is what `console.info(opts)` returns:

```
pages: 1
type: "POST"
url: "/app_dev.php/users/"
```

**Comment by stephanvierkant** [comment]
This is a good chance to add parameter types and return types to the new methods. What you you think?

**Pull request merged**
