### PR TITLE
Reduced code duplication and load only filter JS after all resources have loaded

### PR DESCRIPTION
**Pull request by sweoggy**
Fixes issue where some or all resources required for various filters, such as JQuery and Moment, hasn't been loaded yet when executing filter scripts.

### CODE REVIEW

**Comment by Seb33300** [comment]
you should use spaces instead of tabs

**Comment by Seb33300** [comment]
You should use `sg_datatables_render_html(datatable)` and `sg_datatables_render_js(datatable)` instead of `sg_datatables_render(datatable)` if you want to separate html / javascript render so you can put javascript code in the footer of your page.

**Comment by sweoggy** [comment]
@Seb33300 I am using them separately (`sg_datatables_render_html(datatable)` and `sg_datatables_render_js(datatable)`) in such a way the JavaScript is at the bottom.

**Comment by sweoggy** [comment]
@stwe any chance of a merge? Using window.addEventListener("load", function () is the only way to ensure all externally linked dependencies are properly loaded such as JQuery and moment.

**Comment by sweoggy** [comment]
@stwe Any news? Would be great to be able to use the more advanced filters offered by this bundle such as datefilter.

**Comment by stwe** [comment]
in this week is planned:
- I'll add the datatable events support to the bundle
- review and add PR with DoctrineCaching
- close issue mit multiple tables on same page

Then I'll set a tag for a beta1. I think it's time.

And after that, I will load my javascrips in the documents footer and test the bundle with it ...

**Comment by sweoggy** [comment]
@stwe alright, thanks!

**Comment by stephanvierkant** [comment]
I'm trying to implement Webpack and I'm experience the same issue here. Especially MomentJS is very hard to use with Webpack.

Any update on this issue?

**Comment by sweoggy** [comment]
After about a year with little to no activity I have decided to close this PR as it would require a rebase and other work. I have instead created a fork where this PR has been incorporated.

**Comment by mshd** [comment]
@stwe Hello, is it possible now to add the daterangefilter to the bottom of the script.
`        $("#sg-datatables-searchlog_datatable-head-filter-1").daterangepicker({`
still produces
`ReferenceError: $ is not defined`

Please let me know what I can do, without having to move the JS to the header

**Pull request closed without merging**
