### PR TITLE
Fixed crash on joins in DatatableQueryBuilder

### PR DESCRIPTION
**Pull request by sweoggy**
Now correctly calls one of QueryBuilder's join functions

### CODE REVIEW

**Comment by stwe** [comment]
Question: What bug is fixed here?

**Comment by sweoggy** [comment]
The following code crash without this fix:

```
        $datatable = $this->get('app.datatable.service.news');
	$datatable->buildDatatable();

        /* @var $responseService DatatableResponse */
	$responseService = $this->get('sg_datatables.response');
	$responseService->setDatatable($datatable);

	$datatableQueryBuilder = $responseService->getDatatableQueryBuilder();
        $qB = $datatableQueryBuilder->getQb();
        $qB->andWhere('actions.employer = :employer'); // <---- Where is added here...
        $qB->setParameter('employer', $this->getUser()->getEmployer());
        $datatableQueryBuilder->setQb($qB);
	$datatableQueryBuilder->buildQuery(); // <---- ... causes crash when building query

	return $responseService->getResponse()
```

**Comment by Seb33300** [comment]
Your code also crash with the fix.

This is what I am doing to make changes on the query builder without issues.
I build the query before making change on the query builder:
```
// Datatable
$datatable = $this->get('app.datatable.name');
$datatable->buildDatatable([], $licenseSuite);

// Response service
$responseService = $this->get('sg_datatables.response');
$responseService->setDatatable($datatable);

// Datatable query builder
$datatableQueryBuilder = $responseService->getDatatableQueryBuilder();
$datatableQueryBuilder->buildQuery();

$queryBuilder = $datatableQueryBuilder->getQb();
$queryBuilder->andWhere('actions.employer = :employer');
$queryBuilder->setParameter('employer', $this->getUser()->getEmployer());

return $responseService->getResponse();
```

The only issue I have is that the counter under the datatable display incorrect values.

**Comment by sweoggy** [comment]
Well, I just tested it once more and it works just fine.

Without fix:
sg datatablebundle without fix

With fix:
sg datatablebundle with fix

This is on PHP 7.1, tried both on Windows and Ubuntu.

**Comment by Seb33300** [comment]
Working fine on PHP 5.6.

It's a PHP 7 backward incompatible changes:
http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect

We have to use `$obj->{$array['key']}` now with PHP 7.

**Comment by stwe** [comment]
good to know. Thank you.

**Comment by sweoggy** [comment]
Any chance of merge? @stwe 

Perhaps you might want to rerun Travis :)

**Comment by stwe** [comment]
@sweoggy Yes, of course. But not immediately.

**Pull request merged**
